### ISSUE TITLE
Bug: `DateBetween` filter crashes - heap-buffer-overflow

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/LAPIS-SILO#65]
How to reproduce the bug:
* start SILO
* send a `DateBetween` filter expression, e.g. 
```
POST http://localhost:8081/query
Content-Type: application/json

{
  "action": {
    "type": "Aggregated"
  },
  "filterExpression": {
    "type": "DateBetween",
    "from": "2021-03-18",
    "to": null
  }
}
```
* SILO crashes:
```
==53518==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020022d7698 at pc 0x557fbe913c30 bp 0x7f84a77e6bf0 sp 0x7f84a77e6be8
READ of size 8 at 0x6020022d7698 thread T21
    #0 0x557fbe913c2f in fmt::v9::detail::value<fmt::v9::basic_format_context<fmt::v9::appender, char> > fmt::v9::detail::make_value<fmt::v9::basic_format_context<fmt::v9::appender, char>, long const&>(long const&) /home/engelnif/.conan2/p/fmt6483714aaa35b/p/include/fmt/core.h:1735:47
    #1 0x557fbe913c2f in fmt::v9::detail::value<fmt::v9::basic_format_context<fmt::v9::appender, char> > fmt::v9::detail::make_arg<true, fmt::v9::basic_format_context<fmt::v9::appender, char>, (fmt::v9::detail::type)3, long const&, 0>(long const&) /home/engelnif/.conan2/p/fmt6483714aaa35b/p/include/fmt/core.h:1777:10
    #2 0x557fbe913c2f in fmt::v9::format_arg_store<fmt::v9::basic_format_context<fmt::v9::appender, char>, long>::format_arg_store<long const&>(long const&) /home/engelnif/.conan2/p/fmt6483714aaa35b/p/include/fmt/core.h:1899:15
    #3 0x557fbe913c2f in fmt::v9::format_arg_store<fmt::v9::basic_format_context<fmt::v9::appender, char>, std::remove_cv<std::remove_reference<long const&>::type>::type> fmt::v9::make_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char>, long const&>(long const&) /home/engelnif/.conan2/p/fmt6483714aaa35b/p/include/fmt/core.h:1918:10
    #4 0x557fbe91294a in void spdlog::logger::log_<long const&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_string_view<char>, long const&) /home/engelnif/.conan2/p/spdlo93109983ef254/p/include/spdlog/logger.h:374:54
    #5 0x557fbe8f559b in void spdlog::logger::log<long const&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_format_string<char, fmt::v9::type_identity<long const&>::type>, long const&) /home/engelnif/.conan2/p/spdlo93109983ef254/p/include/spdlog/logger.h:90:9
    #6 0x557fbe8c745f in silo::DateBetweenExpression::evaluate(silo::Database const&, silo::DatabasePartition const&) /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo/query_engine/query_engine.cpp:759:7
    #7 0x557fbe8af269 in silo::executeQuery(silo::Database const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo/query_engine/query_engine.cpp:1311:26
    #8 0x557fbe8adce8 in silo::QueryEngine::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo/query_engine/query_engine.cpp:40:11
    #9 0x557fbe7654b7 in silo_api::QueryHandler::post(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo_api/query_handler.cpp:52:46
    #10 0x557fbe771074 in silo_api::RestResource::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo_api/rest_resource.cpp:30:14
    #11 0x557fbe6e7321 in silo_api::ErrorRequestHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo_api/error_request_handler.cpp:16:24
    #12 0x557fbe75e388 in silo_api::LoggingRequestHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /home/engelnif/src/GenSpectrum/LAPIS-SILO/src/silo_api/logging_request_handler.cpp:16:21
    #13 0x557fbeab160f in Poco::Net::HTTPServerConnection::run() /home/engelnif/.conan2/p/t/poco1b18d02af1b83/b/src/Net/src/HTTPServerConnection.cpp:87:17
    #14 0x557fbeac1058 in Poco::Net::TCPServerConnection::start() /home/engelnif/.conan2/p/t/poco1b18d02af1b83/b/src/Net/src/TCPServerConnection.cpp:43:3
    #15 0x557fbeaab3dd in Poco::Net::TCPServerDispatcher::run() /home/engelnif/.conan2/p/t/poco1b18d02af1b83/b/src/Net/src/TCPServerDispatcher.cpp:119:20
    #16 0x557fbeb9b423 in Poco::PooledThread::run() /home/engelnif/.conan2/p/t/poco1b18d02af1b83/b/src/Foundation/src/ThreadPool.cpp:199:14
    #17 0x557fbeb988d9 in Poco::(anonymous namespace)::RunnableHolder::run() /home/engelnif/.conan2/p/t/poco1b18d02af1b83/b/src/Foundation/src/Thread.cpp:56:11
    #18 0x557fbeb9752f in Poco::ThreadImpl::runnableEntry(void*) /home/engelnif/.conan2/p/t/poco1b18d02af1b83/b/src/Foundation/src/Thread_POSIX.cpp:358:27
    #19 0x7f84cae94b42 in start_thread nptl/./nptl/pthread_create.c:442:8
    #20 0x7f84caf269ff  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

https://github.com/GenSpectrum/LAPIS-SILO/commit/39481ef5cd5c19f20fde341b6642d73661ca3ae8 contains some additional log statements that I used to track the problem:
* The database is built using the `Architecture::MAX_PARTITIONS`: every partition contains exactly one chunk.
* The chunks contain an `offset`.
* The DateBetween filter expression acesses `database_partition.meta_store.sequence_id_to_date[chunk.offset]` when evaluating.

In the `Architecture::MAX_PARTITIONS`, the chunk's offset is global, while the DateBetween filter expression expects it to be local on every partition. Thus the index is out of range when accessing `database_partition.meta_store.sequence_id_to_date[chunk.offset]`.

**Comment by fengelniederhammer** [comment]
Another observation: This only happens in a debug build. In release build, DateBetween works. It "only" seems to be the address sanitizer that let's complains here.
